# env:
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: postgres
#   DATABASE_USER: postgres
#   DATABASE_PASSWORD: 	postgres

name: Run RSPec

on:
  push:
    branches:
      - main
      - test
      - dev

jobs:
  build:
    name: Set-up environment
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        # image: postgres12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
        - 5432:5432

      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
#          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Install PostgreSQL client
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create database
        env:
          REDIS_URL: redis://localhost:6379/0
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test

        run: bundler exec rspec .


  # simplecov-test:
  #   name: SimpleCov
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #         bundler-cache: true
    # - name: Download all workflow run artifacts
    #   uses: actions/download-artifact@v2
    #   if: always()
